# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OhsomePlugin
                                 A QGIS plugin
 Query Ohsome directly from QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-23
        copyright            : (C) 2020 by Julian Psotta
        email                : julianpsotta@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
import configparser
import os
from datetime import datetime


def classFactory(iface):  # pylint: disable=invalid-name
    """Load OhsomePlugin class from file OhsomePlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .ohsome_plugin import OhsomePlugin

    return OhsomePlugin(iface)


# Define plugin wide constants
PLUGIN_NAME = "Ohsome API Plugin"
DEFAULT_COLOR = "#a8b1f5"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

RESOURCE_PREFIX = ":plugins/OhsomeTools/img/"
CONFIG_PATH = os.path.join(BASE_DIR, "config.yml")

# Read metadata.txt
METADATA = configparser.ConfigParser()
METADATA.read(os.path.join(BASE_DIR, "metadata.txt"), encoding="utf-8")
today = datetime.today()

__version__ = METADATA["general"]["version"]
__author__ = METADATA["general"]["author"]
__email__ = METADATA["general"]["email"]
__web__ = METADATA["general"]["homepage"]
__date__ = today.strftime("%Y-%m-%d")
__copyright__ = "(C) {} by {}".format(today.year, __author__)
