# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OhsomeQgisDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OhsomeQgisDialogBase(object):
    def setupUi(self, OhsomeQgisDialogBase):
        OhsomeQgisDialogBase.setObjectName("OhsomeQgisDialogBase")
        OhsomeQgisDialogBase.resize(463, 928)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            OhsomeQgisDialogBase.sizePolicy().hasHeightForWidth()
        )
        OhsomeQgisDialogBase.setSizePolicy(sizePolicy)
        OhsomeQgisDialogBase.setSizeGripEnabled(True)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(OhsomeQgisDialogBase)
        self.verticalLayout_5.setSizeConstraint(
            QtWidgets.QLayout.SetMinAndMaxSize
        )
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.resources_group = QtWidgets.QGroupBox(OhsomeQgisDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.resources_group.sizePolicy().hasHeightForWidth()
        )
        self.resources_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resources_group.setFont(font)
        self.resources_group.setAlignment(QtCore.Qt.AlignCenter)
        self.resources_group.setFlat(False)
        self.resources_group.setObjectName("resources_group")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.resources_group)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.api_label = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.api_label.setFont(font)
        self.api_label.setAlignment(QtCore.Qt.AlignCenter)
        self.api_label.setOpenExternalLinks(True)
        self.api_label.setObjectName("api_label")
        self.horizontalLayout_3.addWidget(self.api_label)
        self.ohsome_label = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ohsome_label.setFont(font)
        self.ohsome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ohsome_label.setOpenExternalLinks(True)
        self.ohsome_label.setObjectName("ohsome_label")
        self.horizontalLayout_3.addWidget(self.ohsome_label)
        self.hex_label = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hex_label.setFont(font)
        self.hex_label.setAlignment(QtCore.Qt.AlignCenter)
        self.hex_label.setOpenExternalLinks(True)
        self.hex_label.setObjectName("hex_label")
        self.horizontalLayout_3.addWidget(self.hex_label)
        self.verticalLayout_5.addWidget(self.resources_group)
        self.groupBox_4 = QtWidgets.QGroupBox(OhsomeQgisDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_4.sizePolicy().hasHeightForWidth()
        )
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.provider_combo = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.provider_combo.sizePolicy().hasHeightForWidth()
        )
        self.provider_combo.setSizePolicy(sizePolicy)
        self.provider_combo.setMinimumSize(QtCore.QSize(150, 25))
        self.provider_combo.setObjectName("provider_combo")
        self.gridLayout_4.addWidget(self.provider_combo, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.provider_refresh = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.provider_refresh.sizePolicy().hasHeightForWidth()
        )
        self.provider_refresh.setSizePolicy(sizePolicy)
        self.provider_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/plugins/OhsomeQgis/img/icon_refresh.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.provider_refresh.setIcon(icon)
        self.provider_refresh.setObjectName("provider_refresh")
        self.gridLayout_4.addWidget(self.provider_refresh, 0, 2, 1, 1)
        self.provider_config = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.provider_config.sizePolicy().hasHeightForWidth()
        )
        self.provider_config.setSizePolicy(sizePolicy)
        self.provider_config.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/plugins/OhsomeQgis/img/icon_settings.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.provider_config.setIcon(icon1)
        self.provider_config.setObjectName("provider_config")
        self.gridLayout_4.addWidget(self.provider_config, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ohsome_spec_selection_combo = QtWidgets.QComboBox(self.frame_3)
        self.ohsome_spec_selection_combo.setObjectName(
            "ohsome_spec_selection_combo"
        )
        self.horizontalLayout_7.addWidget(self.ohsome_spec_selection_combo)
        self.ohsome_spec_preference_combo = QtWidgets.QComboBox(self.frame_3)
        self.ohsome_spec_preference_combo.setObjectName(
            "ohsome_spec_preference_combo"
        )
        self.horizontalLayout_7.addWidget(self.ohsome_spec_preference_combo)
        self.ohsome_spec_preference_endpoint = QtWidgets.QComboBox(self.frame_3)
        self.ohsome_spec_preference_endpoint.setObjectName(
            "ohsome_spec_preference_endpoint"
        )
        self.horizontalLayout_7.addWidget(self.ohsome_spec_preference_endpoint)
        self.gridLayout_2.addWidget(self.frame_3, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.widget_3 = QtWidgets.QWidget(OhsomeQgisDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_3.sizePolicy().hasHeightForWidth()
        )
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5.addWidget(self.widget_3)
        self.request_types_widget = QtWidgets.QTabWidget(OhsomeQgisDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.request_types_widget.sizePolicy().hasHeightForWidth()
        )
        self.request_types_widget.setSizePolicy(sizePolicy)
        self.request_types_widget.setMaximumSize(
            QtCore.QSize(16777215, 16777215)
        )
        self.request_types_widget.setUsesScrollButtons(True)
        self.request_types_widget.setObjectName("request_types_widget")
        self.centroid_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centroid_tab.sizePolicy().hasHeightForWidth()
        )
        self.centroid_tab.setSizePolicy(sizePolicy)
        self.centroid_tab.setObjectName("centroid_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centroid_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget = QtWidgets.QWidget(self.centroid_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget.sizePolicy().hasHeightForWidth()
        )
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_7 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_7.sizePolicy().hasHeightForWidth()
        )
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.centroid_list_point_add = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centroid_list_point_add.sizePolicy().hasHeightForWidth()
        )
        self.centroid_list_point_add.setSizePolicy(sizePolicy)
        self.centroid_list_point_add.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/plugins/OhsomeQgis/img/icon_add.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.centroid_list_point_add.setIcon(icon2)
        self.centroid_list_point_add.setObjectName("centroid_list_point_add")
        self.gridLayout_7.addWidget(self.centroid_list_point_add, 0, 0, 1, 1)
        self.centroid_list_point_clear = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centroid_list_point_clear.sizePolicy().hasHeightForWidth()
        )
        self.centroid_list_point_clear.setSizePolicy(sizePolicy)
        self.centroid_list_point_clear.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/plugins/OhsomeQgis/img/icon_clear.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.centroid_list_point_clear.setIcon(icon3)
        self.centroid_list_point_clear.setObjectName(
            "centroid_list_point_clear"
        )
        self.gridLayout_7.addWidget(self.centroid_list_point_clear, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_7, 1, 0, 1, 1)
        self.centroid_radius_input = QtWidgets.QSpinBox(self.widget)
        self.centroid_radius_input.setAccessibleDescription("")
        self.centroid_radius_input.setMaximum(99)
        self.centroid_radius_input.setProperty("value", 10)
        self.centroid_radius_input.setObjectName("centroid_radius_input")
        self.gridLayout.addWidget(self.centroid_radius_input, 0, 1, 1, 1)
        self.centroid_radius_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centroid_radius_label.sizePolicy().hasHeightForWidth()
        )
        self.centroid_radius_label.setSizePolicy(sizePolicy)
        self.centroid_radius_label.setObjectName("centroid_radius_label")
        self.gridLayout.addWidget(self.centroid_radius_label, 0, 0, 1, 1)
        self.ohsome_centroid_location_list = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ohsome_centroid_location_list.sizePolicy().hasHeightForWidth()
        )
        self.ohsome_centroid_location_list.setSizePolicy(sizePolicy)
        self.ohsome_centroid_location_list.setMinimumSize(QtCore.QSize(0, 0))
        self.ohsome_centroid_location_list.setMaximumSize(
            QtCore.QSize(16777215, 16777215)
        )
        self.ohsome_centroid_location_list.setFrameShadow(
            QtWidgets.QFrame.Sunken
        )
        self.ohsome_centroid_location_list.setSelectionMode(
            QtWidgets.QAbstractItemView.MultiSelection
        )
        self.ohsome_centroid_location_list.setResizeMode(
            QtWidgets.QListView.Fixed
        )
        self.ohsome_centroid_location_list.setObjectName(
            "ohsome_centroid_location_list"
        )
        self.gridLayout.addWidget(
            self.ohsome_centroid_location_list, 1, 1, 1, 1
        )
        self.gridLayout_8.addWidget(self.widget, 0, 0, 1, 1)
        self.request_types_widget.addTab(self.centroid_tab, "")
        self.layer_tab = QtWidgets.QWidget()
        self.layer_tab.setObjectName("layer_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layer_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.layer_input = gui.QgsMapLayerComboBox(self.layer_tab)
        self.layer_input.setObjectName("layer_input")
        self.gridLayout_6.addWidget(self.layer_input, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.layer_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_5.sizePolicy().hasHeightForWidth()
        )
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_8.sizePolicy().hasHeightForWidth()
        )
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.layer_list_remove = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.layer_list_remove.sizePolicy().hasHeightForWidth()
        )
        self.layer_list_remove.setSizePolicy(sizePolicy)
        self.layer_list_remove.setText("")
        self.layer_list_remove.setIcon(icon3)
        self.layer_list_remove.setObjectName("layer_list_remove")
        self.gridLayout_9.addWidget(self.layer_list_remove, 1, 0, 1, 1)
        self.layer_list_add = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.layer_list_add.sizePolicy().hasHeightForWidth()
        )
        self.layer_list_add.setSizePolicy(sizePolicy)
        self.layer_list_add.setText("")
        self.layer_list_add.setIcon(icon2)
        self.layer_list_add.setObjectName("layer_list_add")
        self.gridLayout_9.addWidget(self.layer_list_add, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_8, 0, 0, 1, 1)
        self.layer_list = QtWidgets.QListWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.layer_list.sizePolicy().hasHeightForWidth()
        )
        self.layer_list.setSizePolicy(sizePolicy)
        self.layer_list.setMinimumSize(QtCore.QSize(0, 0))
        self.layer_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.layer_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.layer_list.setSelectionMode(
            QtWidgets.QAbstractItemView.MultiSelection
        )
        self.layer_list.setResizeMode(QtWidgets.QListView.Fixed)
        self.layer_list.setObjectName("layer_list")
        self.gridLayout_3.addWidget(self.layer_list, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.widget_5, 1, 0, 1, 1)
        self.request_types_widget.addTab(self.layer_tab, "")
        self.batch_tab = QtWidgets.QWidget()
        self.batch_tab.setObjectName("batch_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.batch_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.batch_tab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.batch_routing_line = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.batch_routing_line.sizePolicy().hasHeightForWidth()
        )
        self.batch_routing_line.setSizePolicy(sizePolicy)
        self.batch_routing_line.setObjectName("batch_routing_line")
        self.horizontalLayout.addWidget(self.batch_routing_line)
        self.batch_routing_point = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.batch_routing_point.sizePolicy().hasHeightForWidth()
        )
        self.batch_routing_point.setSizePolicy(sizePolicy)
        self.batch_routing_point.setObjectName("batch_routing_point")
        self.horizontalLayout.addWidget(self.batch_routing_point)
        self.batch_routing_points = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.batch_routing_points.sizePolicy().hasHeightForWidth()
        )
        self.batch_routing_points.setSizePolicy(sizePolicy)
        self.batch_routing_points.setObjectName("batch_routing_points")
        self.horizontalLayout.addWidget(self.batch_routing_points)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.batch_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.batch_iso_point = QtWidgets.QPushButton(self.groupBox_2)
        self.batch_iso_point.setObjectName("batch_iso_point")
        self.horizontalLayout_4.addWidget(self.batch_iso_point)
        self.batch_iso_layer = QtWidgets.QPushButton(self.groupBox_2)
        self.batch_iso_layer.setObjectName("batch_iso_layer")
        self.horizontalLayout_4.addWidget(self.batch_iso_layer)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.batch_tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.batch_matrix = QtWidgets.QPushButton(self.groupBox_3)
        self.batch_matrix.setObjectName("batch_matrix")
        self.horizontalLayout_5.addWidget(self.batch_matrix)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Minimum,
            QtWidgets.QSizePolicy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem)
        self.request_types_widget.addTab(self.batch_tab, "")
        self.verticalLayout_5.addWidget(self.request_types_widget)
        self.configuration_group_box = gui.QgsCollapsibleGroupBox(
            OhsomeQgisDialogBase
        )
        self.configuration_group_box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.configuration_group_box.sizePolicy().hasHeightForWidth()
        )
        self.configuration_group_box.setSizePolicy(sizePolicy)
        self.configuration_group_box.setMaximumSize(
            QtCore.QSize(16777215, 16777215)
        )
        self.configuration_group_box.setAutoFillBackground(False)
        self.configuration_group_box.setFlat(True)
        self.configuration_group_box.setCheckable(False)
        self.configuration_group_box.setChecked(False)
        self.configuration_group_box.setCollapsed(False)
        self.configuration_group_box.setScrollOnExpand(False)
        self.configuration_group_box.setSaveCollapsedState(False)
        self.configuration_group_box.setObjectName("configuration_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(
            self.configuration_group_box
        )
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.check_activate_temporal = QtWidgets.QCheckBox(
            self.configuration_group_box
        )
        self.check_activate_temporal.setChecked(True)
        self.check_activate_temporal.setObjectName("check_activate_temporal")
        self.verticalLayout_4.addWidget(self.check_activate_temporal)
        self.check_show_metadata = QtWidgets.QCheckBox(
            self.configuration_group_box
        )
        self.check_show_metadata.setEnabled(True)
        self.check_show_metadata.setChecked(False)
        self.check_show_metadata.setObjectName("check_show_metadata")
        self.verticalLayout_4.addWidget(self.check_show_metadata)
        self.intervals_group = gui.QgsCollapsibleGroupBox(
            self.configuration_group_box
        )
        self.intervals_group.setCollapsed(False)
        self.intervals_group.setObjectName("intervals_group")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.intervals_group)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_years = QtWidgets.QLabel(self.intervals_group)
        self.label_years.setObjectName("label_years")
        self.gridLayout_10.addWidget(self.label_years, 2, 1, 1, 1)
        self.interval_days = QtWidgets.QSpinBox(self.intervals_group)
        self.interval_days.setMaximum(31)
        self.interval_days.setProperty("value", 1)
        self.interval_days.setObjectName("interval_days")
        self.gridLayout_10.addWidget(self.interval_days, 3, 4, 1, 1)
        self.label_months = QtWidgets.QLabel(self.intervals_group)
        self.label_months.setObjectName("label_months")
        self.gridLayout_10.addWidget(self.label_months, 2, 2, 1, 1)
        self.interval_years = QtWidgets.QSpinBox(self.intervals_group)
        self.interval_years.setAccessibleDescription("")
        self.interval_years.setMaximum(99)
        self.interval_years.setProperty("value", 0)
        self.interval_years.setObjectName("interval_years")
        self.gridLayout_10.addWidget(self.interval_years, 3, 1, 1, 1)
        self.date_end_label = QtWidgets.QLabel(self.intervals_group)
        self.date_end_label.setObjectName("date_end_label")
        self.gridLayout_10.addWidget(self.date_end_label, 4, 4, 1, 1)
        self.date_start_label = QtWidgets.QLabel(self.intervals_group)
        self.date_start_label.setObjectName("date_start_label")
        self.gridLayout_10.addWidget(self.date_start_label, 4, 1, 1, 1)
        self.interval_months = QtWidgets.QSpinBox(self.intervals_group)
        self.interval_months.setMaximum(12)
        self.interval_months.setObjectName("interval_months")
        self.gridLayout_10.addWidget(self.interval_months, 3, 2, 1, 1)
        self.date_end = QtWidgets.QDateEdit(self.intervals_group)
        self.date_end.setDateTime(
            QtCore.QDateTime(QtCore.QDate(2007, 10, 9), QtCore.QTime(0, 0, 0))
        )
        self.date_end.setMinimumDateTime(
            QtCore.QDateTime(QtCore.QDate(2007, 10, 9), QtCore.QTime(0, 0, 0))
        )
        self.date_end.setMinimumDate(QtCore.QDate(2007, 10, 9))
        self.date_end.setObjectName("date_end")
        self.gridLayout_10.addWidget(self.date_end, 5, 4, 1, 1)
        self.label_days = QtWidgets.QLabel(self.intervals_group)
        self.label_days.setObjectName("label_days")
        self.gridLayout_10.addWidget(self.label_days, 2, 4, 1, 1)
        self.date_start = QtWidgets.QDateEdit(self.intervals_group)
        self.date_start.setDateTime(
            QtCore.QDateTime(QtCore.QDate(2007, 10, 8), QtCore.QTime(0, 0, 0))
        )
        self.date_start.setMinimumDateTime(
            QtCore.QDateTime(QtCore.QDate(2007, 10, 8), QtCore.QTime(0, 0, 0))
        )
        self.date_start.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.date_start.setMinimumDate(QtCore.QDate(2007, 10, 8))
        self.date_start.setTimeSpec(QtCore.Qt.LocalTime)
        self.date_start.setObjectName("date_start")
        self.gridLayout_10.addWidget(self.date_start, 5, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.intervals_group)
        self.filter_frame = QtWidgets.QFrame(self.configuration_group_box)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_frame.sizePolicy().hasHeightForWidth()
        )
        self.filter_frame.setSizePolicy(sizePolicy)
        self.filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame.setObjectName("filter_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.filter_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.filter_label = QtWidgets.QLabel(self.filter_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_label.sizePolicy().hasHeightForWidth()
        )
        self.filter_label.setSizePolicy(sizePolicy)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout_6.addWidget(self.filter_label)
        self.filter_input = QtWidgets.QPlainTextEdit(self.filter_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Maximum,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_input.sizePolicy().hasHeightForWidth()
        )
        self.filter_input.setSizePolicy(sizePolicy)
        self.filter_input.setMaximumSize(QtCore.QSize(331, 101))
        self.filter_input.setObjectName("filter_input")
        self.horizontalLayout_6.addWidget(self.filter_input)
        self.verticalLayout_4.addWidget(self.filter_frame)
        self.verticalLayout_5.addWidget(self.configuration_group_box)
        self.ohsome_log_group = gui.QgsCollapsibleGroupBox(OhsomeQgisDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ohsome_log_group.sizePolicy().hasHeightForWidth()
        )
        self.ohsome_log_group.setSizePolicy(sizePolicy)
        self.ohsome_log_group.setMinimumSize(QtCore.QSize(0, 0))
        self.ohsome_log_group.setMaximumSize(QtCore.QSize(16777215, 28))
        self.ohsome_log_group.setFlat(True)
        self.ohsome_log_group.setCollapsed(True)
        self.ohsome_log_group.setSaveCollapsedState(False)
        self.ohsome_log_group.setObjectName("ohsome_log_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ohsome_log_group)
        self.verticalLayout_2.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.debug_text = QtWidgets.QTextBrowser(self.ohsome_log_group)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.debug_text.sizePolicy().hasHeightForWidth()
        )
        self.debug_text.setSizePolicy(sizePolicy)
        self.debug_text.setMinimumSize(QtCore.QSize(0, 80))
        self.debug_text.setMaximumSize(QtCore.QSize(16777215, 80))
        self.debug_text.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.debug_text.setTabStopWidth(80)
        self.debug_text.setOpenExternalLinks(True)
        self.debug_text.setObjectName("debug_text")
        self.verticalLayout_2.addWidget(self.debug_text)
        self.verticalLayout_5.addWidget(self.ohsome_log_group)
        self.control_widget = QtWidgets.QWidget(OhsomeQgisDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.control_widget.sizePolicy().hasHeightForWidth()
        )
        self.control_widget.setSizePolicy(sizePolicy)
        self.control_widget.setObjectName("control_widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.control_widget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.help_button = QtWidgets.QPushButton(self.control_widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.help_button.sizePolicy().hasHeightForWidth()
        )
        self.help_button.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/plugins/OhsomeQgis/img/icon_help.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.help_button.setIcon(icon4)
        self.help_button.setObjectName("help_button")
        self.horizontalLayout_8.addWidget(self.help_button)
        self.about_button = QtWidgets.QPushButton(self.control_widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/plugins/OhsomeQgis/img/icon_about.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.about_button.setIcon(icon5)
        self.about_button.setObjectName("about_button")
        self.horizontalLayout_8.addWidget(self.about_button)
        self.global_buttons = QtWidgets.QDialogButtonBox(self.control_widget)
        self.global_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.global_buttons.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.global_buttons.setObjectName("global_buttons")
        self.horizontalLayout_8.addWidget(self.global_buttons)
        self.verticalLayout_5.addWidget(self.control_widget)
        self.resources_group.raise_()
        self.control_widget.raise_()
        self.ohsome_log_group.raise_()
        self.request_types_widget.raise_()
        self.widget_3.raise_()
        self.configuration_group_box.raise_()
        self.groupBox_4.raise_()

        self.retranslateUi(OhsomeQgisDialogBase)
        self.request_types_widget.setCurrentIndex(0)
        self.global_buttons.accepted.connect(OhsomeQgisDialogBase.accept)
        self.global_buttons.rejected.connect(OhsomeQgisDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(OhsomeQgisDialogBase)

    def retranslateUi(self, OhsomeQgisDialogBase):
        _translate = QtCore.QCoreApplication.translate
        OhsomeQgisDialogBase.setWindowTitle(
            _translate("OhsomeQgisDialogBase", "Ohsome Tools")
        )
        self.resources_group.setTitle(
            _translate("OhsomeQgisDialogBase", "Resources")
        )
        self.api_label.setText(
            _translate(
                "OhsomeQgisDialogBase",
                '<html><head/><body><p><a href="https://docs.ohsome.org/ohsome-api/stable/"><span style=" font-size:12pt; font-weight:600; text-decoration: underline; color:#2eb8e6;">API DOCS</span></a></p></body></html>',
            )
        )
        self.ohsome_label.setText(
            _translate(
                "OhsomeQgisDialogBase",
                '<html><head/><body><p><a href="https://heigit.org/big-spatial-data-analytics-en/ohsome/"><span style=" font-size:14pt; font-weight:600; text-decoration: underline; color:#2eb8e6;">OHSOME</span></a></p></body></html>',
            )
        )
        self.hex_label.setText(
            _translate(
                "OhsomeQgisDialogBase",
                '<html><head/><body><p><a href="https://ohsome.org/apps/osm-history-explorer/"><span style=" font-size:12pt; font-weight:600; text-decoration: underline; color:#2eb8e6;">HEX</span></a></p></body></html>',
            )
        )
        self.groupBox_4.setTitle(
            _translate("OhsomeQgisDialogBase", "Endpoint Selections")
        )
        self.label_15.setText(_translate("OhsomeQgisDialogBase", "Provider"))
        self.provider_refresh.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Refresh the provider list. Needed after a provider was added or deleted.",
            )
        )
        self.provider_config.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Shortcut to Web ► ORS Tools ► Provider Settings",
            )
        )
        self.ohsome_spec_selection_combo.setToolTip(
            _translate("OhsomeQgisDialogBase", "Ohsome Endpoint")
        )
        self.ohsome_spec_preference_combo.setToolTip(
            _translate("OhsomeQgisDialogBase", "Request preference")
        )
        self.ohsome_spec_preference_combo.setPlaceholderText(
            _translate("OhsomeQgisDialogBase", "Spec")
        )
        self.ohsome_spec_preference_endpoint.setToolTip(
            _translate("OhsomeQgisDialogBase", "Request preference")
        )
        self.centroid_list_point_add.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "<html><head/><body><p>Add centroids interactively from the map canvas.</p><p>Double-click will terminate centroid selection.</p></body></html>",
            )
        )
        self.centroid_list_point_clear.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "<html><head/><body><p>If centroids are selected in the list, only these will be deleted. Else all centroids will be deleted.</p></body></html>",
            )
        )
        self.centroid_radius_input.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                '<html><head/><body><p>Add a centroid radius <span style=" text-decoration: underline;">in meters</span> per centroid. Default is <span style=" text-decoration: underline;">10 meters</span>.</p></body></html>',
            )
        )
        self.centroid_radius_label.setText(
            _translate("OhsomeQgisDialogBase", "Radius")
        )
        self.ohsome_centroid_location_list.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Select centroids from the map with the given radius!",
            )
        )
        self.request_types_widget.setTabText(
            self.request_types_widget.indexOf(self.centroid_tab),
            _translate("OhsomeQgisDialogBase", "Centroid"),
        )
        self.layer_input.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "<html><head/><body><p>Select Polygon / MultiPolygon layers to query with.</p></body></html>",
            )
        )
        self.layer_list_remove.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "<html><head/><body><p>If layers are selected in the list, only these will be deleted.</p></body></html>",
            )
        )
        self.layer_list_add.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "<html><head/><body><p>Add layers interactively from your layer list.</p></body></html>",
            )
        )
        self.layer_list.setToolTip(
            _translate(
                "OhsomeQgisDialogBase", "Select layers from your layer list!"
            )
        )
        self.request_types_widget.setTabText(
            self.request_types_widget.indexOf(self.layer_tab),
            _translate("OhsomeQgisDialogBase", "Layer Selection"),
        )
        self.groupBox.setTitle(_translate("OhsomeQgisDialogBase", "Directions"))
        self.batch_routing_line.setText(
            _translate("OhsomeQgisDialogBase", "Polylines Layer")
        )
        self.batch_routing_point.setText(
            _translate("OhsomeQgisDialogBase", "Points (1 Layer)")
        )
        self.batch_routing_points.setText(
            _translate("OhsomeQgisDialogBase", "Points (2 Layer)")
        )
        self.groupBox_2.setTitle(
            _translate("OhsomeQgisDialogBase", "Isochrones")
        )
        self.batch_iso_point.setText(
            _translate("OhsomeQgisDialogBase", "Isochrones from Point")
        )
        self.batch_iso_layer.setText(
            _translate("OhsomeQgisDialogBase", "Isochrones from Layer")
        )
        self.groupBox_3.setTitle(_translate("OhsomeQgisDialogBase", "Matrix"))
        self.batch_matrix.setText(_translate("OhsomeQgisDialogBase", "Matrix"))
        self.request_types_widget.setTabText(
            self.request_types_widget.indexOf(self.batch_tab),
            _translate("OhsomeQgisDialogBase", "Batch Jobs"),
        )
        self.configuration_group_box.setTitle(
            _translate("OhsomeQgisDialogBase", "Configuration")
        )
        self.check_activate_temporal.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Automatically enable the temporal feature for new layers.",
            )
        )
        self.check_activate_temporal.setText(
            _translate(
                "OhsomeQgisDialogBase", "Auto enable Qgis temporal feature"
            )
        )
        self.check_show_metadata.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "<html><head/><body><p>Include metadata into the query response. Depending on the request of the request this can increase the response data size significantly.</p></body></html>",
            )
        )
        self.check_show_metadata.setText(
            _translate("OhsomeQgisDialogBase", "Show metadata")
        )
        self.intervals_group.setTitle(
            _translate("OhsomeQgisDialogBase", "Intervals")
        )
        self.label_years.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Run the query every x years. Adjust the time frame accordingly,",
            )
        )
        self.label_years.setText(_translate("OhsomeQgisDialogBase", "Years"))
        self.interval_days.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Run the query every x days. Adjust the time frame accordingly,",
            )
        )
        self.label_months.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Run the query every x months. Adjust the time frame accordingly,",
            )
        )
        self.label_months.setText(_translate("OhsomeQgisDialogBase", "Months"))
        self.interval_years.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                '<html><head/><body><p>Run the query every <span style=" text-decoration: underline;">x</span> years. Adjust the time frame accordingly.</p></body></html>',
            )
        )
        self.date_end_label.setText(
            _translate("OhsomeQgisDialogBase", "Date End")
        )
        self.date_start_label.setText(
            _translate("OhsomeQgisDialogBase", "Date Start")
        )
        self.interval_months.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Run the query every x months. Adjust the time frame accordingly,",
            )
        )
        self.date_end.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                '<html><head/><body><p>Enter your end date. </p><p><br/></p><p>All <span style=" text-decoration: underline;">dates from the </span><span style=" font-weight:600; text-decoration: underline;">9th</span><span style=" text-decoration: underline;"> of Oktober 2007</span> are valid.</p></body></html>',
            )
        )
        self.date_end.setDisplayFormat(
            _translate("OhsomeQgisDialogBase", "dd-MM-yyyy")
        )
        self.label_days.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                "Run the query every x days. Adjust the time frame accordingly,",
            )
        )
        self.label_days.setText(_translate("OhsomeQgisDialogBase", "Days"))
        self.date_start.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                '<html><head/><body><p>Enter your start date. </p><p><br/></p><p>All <span style=" text-decoration: underline;">dates from the </span><span style=" font-weight:600; text-decoration: underline;">8th</span><span style=" text-decoration: underline;"> of Oktober 2007</span> are valid.</p></body></html>',
            )
        )
        self.date_start.setDisplayFormat(
            _translate("OhsomeQgisDialogBase", "dd-MM-yyyy")
        )
        self.filter_label.setText(
            _translate("OhsomeQgisDialogBase", "Filter  ")
        )
        self.filter_input.setToolTip(
            _translate(
                "OhsomeQgisDialogBase",
                '<html><head/><body><p>Enter your desired filter query by using common OpenStreetMap tags. For more information see: <a href="https://docs.ohsome.org/ohsome-api/v1/filter.html"><span style=" text-decoration: underline; color:#2eb8e6;">https://docs.ohsome.org/ohsome-api/v1/filter.html</span></a></p></body></html>',
            )
        )
        self.filter_input.setPlainText(
            _translate("OhsomeQgisDialogBase", "building=yes and type:way")
        )
        self.filter_input.setPlaceholderText(
            _translate("OhsomeQgisDialogBase", "landuse=forest or natural=wood")
        )
        self.ohsome_log_group.setTitle(
            _translate("OhsomeQgisDialogBase", "Log")
        )
        self.debug_text.setPlaceholderText(
            _translate(
                "OhsomeQgisDialogBase",
                "Queries and errors will be printed here.",
            )
        )
        self.help_button.setText(_translate("OhsomeQgisDialogBase", "  Help"))
        self.about_button.setText(_translate("OhsomeQgisDialogBase", "About"))


from qgis import gui
from . import resources_rc
