# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OhsomeQgisDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OhsomeToolsDialogBase(object):
    def setupUi(self, OhsomeToolsDialogBase):
        OhsomeToolsDialogBase.setObjectName("OhsomeToolsDialogBase")
        OhsomeToolsDialogBase.resize(462, 1416)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            OhsomeToolsDialogBase.sizePolicy().hasHeightForWidth()
        )
        OhsomeToolsDialogBase.setSizePolicy(sizePolicy)
        OhsomeToolsDialogBase.setSizeGripEnabled(True)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(OhsomeToolsDialogBase)
        self.verticalLayout_5.setSizeConstraint(
            QtWidgets.QLayout.SetMinAndMaxSize
        )
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.resources_group = QtWidgets.QGroupBox(OhsomeToolsDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.resources_group.sizePolicy().hasHeightForWidth()
        )
        self.resources_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resources_group.setFont(font)
        self.resources_group.setAlignment(QtCore.Qt.AlignCenter)
        self.resources_group.setFlat(False)
        self.resources_group.setObjectName("resources_group")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.resources_group)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.api_label = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.api_label.setFont(font)
        self.api_label.setAlignment(QtCore.Qt.AlignCenter)
        self.api_label.setOpenExternalLinks(True)
        self.api_label.setObjectName("api_label")
        self.horizontalLayout_3.addWidget(self.api_label)
        self.ohsome_label = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ohsome_label.setFont(font)
        self.ohsome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ohsome_label.setOpenExternalLinks(True)
        self.ohsome_label.setObjectName("ohsome_label")
        self.horizontalLayout_3.addWidget(self.ohsome_label)
        self.hex_label = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hex_label.setFont(font)
        self.hex_label.setAlignment(QtCore.Qt.AlignCenter)
        self.hex_label.setOpenExternalLinks(True)
        self.hex_label.setObjectName("hex_label")
        self.horizontalLayout_3.addWidget(self.hex_label)
        self.verticalLayout_5.addWidget(self.resources_group)
        self.groupBox_4 = QtWidgets.QGroupBox(OhsomeToolsDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_4.sizePolicy().hasHeightForWidth()
        )
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.provider_combo = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.provider_combo.sizePolicy().hasHeightForWidth()
        )
        self.provider_combo.setSizePolicy(sizePolicy)
        self.provider_combo.setMinimumSize(QtCore.QSize(150, 25))
        self.provider_combo.setObjectName("provider_combo")
        self.gridLayout_4.addWidget(self.provider_combo, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.provider_refresh = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.provider_refresh.sizePolicy().hasHeightForWidth()
        )
        self.provider_refresh.setSizePolicy(sizePolicy)
        self.provider_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/plugins/ohsomeTools/img/icon_refresh.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.provider_refresh.setIcon(icon)
        self.provider_refresh.setObjectName("provider_refresh")
        self.gridLayout_4.addWidget(self.provider_refresh, 0, 2, 1, 1)
        self.provider_config = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.provider_config.sizePolicy().hasHeightForWidth()
        )
        self.provider_config.setSizePolicy(sizePolicy)
        self.provider_config.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/plugins/ohsomeTools/img/icon_settings.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.provider_config.setIcon(icon1)
        self.provider_config.setObjectName("provider_config")
        self.gridLayout_4.addWidget(self.provider_config, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ohsome_spec_selection_combo = QtWidgets.QComboBox(self.frame_3)
        self.ohsome_spec_selection_combo.setObjectName(
            "ohsome_spec_selection_combo"
        )
        self.horizontalLayout_7.addWidget(self.ohsome_spec_selection_combo)
        self.ohsome_spec_preference_combo = QtWidgets.QComboBox(self.frame_3)
        self.ohsome_spec_preference_combo.setObjectName(
            "ohsome_spec_preference_combo"
        )
        self.horizontalLayout_7.addWidget(self.ohsome_spec_preference_combo)
        self.ohsome_spec_preference_specification = QtWidgets.QComboBox(
            self.frame_3
        )
        self.ohsome_spec_preference_specification.setObjectName(
            "ohsome_spec_preference_specification"
        )
        self.horizontalLayout_7.addWidget(
            self.ohsome_spec_preference_specification
        )
        self.gridLayout_2.addWidget(self.frame_3, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.request_types_widget = QtWidgets.QTabWidget(OhsomeToolsDialogBase)
        self.request_types_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.request_types_widget.sizePolicy().hasHeightForWidth()
        )
        self.request_types_widget.setSizePolicy(sizePolicy)
        self.request_types_widget.setMaximumSize(
            QtCore.QSize(16777215, 16777215)
        )
        self.request_types_widget.setUsesScrollButtons(True)
        self.request_types_widget.setObjectName("request_types_widget")
        self.centroid_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centroid_tab.sizePolicy().hasHeightForWidth()
        )
        self.centroid_tab.setSizePolicy(sizePolicy)
        self.centroid_tab.setObjectName("centroid_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centroid_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget = QtWidgets.QWidget(self.centroid_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget.sizePolicy().hasHeightForWidth()
        )
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.centroid_radius_input = QtWidgets.QSpinBox(self.widget)
        self.centroid_radius_input.setAccessibleDescription("")
        self.centroid_radius_input.setMinimum(1)
        self.centroid_radius_input.setMaximum(999999999)
        self.centroid_radius_input.setProperty("value", 1000)
        self.centroid_radius_input.setObjectName("centroid_radius_input")
        self.gridLayout.addWidget(self.centroid_radius_input, 0, 1, 1, 1)
        self.ohsome_centroid_location_list = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ohsome_centroid_location_list.sizePolicy().hasHeightForWidth()
        )
        self.ohsome_centroid_location_list.setSizePolicy(sizePolicy)
        self.ohsome_centroid_location_list.setMinimumSize(QtCore.QSize(0, 0))
        self.ohsome_centroid_location_list.setMaximumSize(
            QtCore.QSize(16777215, 16777215)
        )
        self.ohsome_centroid_location_list.setFrameShadow(
            QtWidgets.QFrame.Sunken
        )
        self.ohsome_centroid_location_list.setSelectionMode(
            QtWidgets.QAbstractItemView.MultiSelection
        )
        self.ohsome_centroid_location_list.setResizeMode(
            QtWidgets.QListView.Fixed
        )
        self.ohsome_centroid_location_list.setObjectName(
            "ohsome_centroid_location_list"
        )
        self.gridLayout.addWidget(
            self.ohsome_centroid_location_list, 1, 1, 1, 1
        )
        self.widget_7 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_7.sizePolicy().hasHeightForWidth()
        )
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.centroid_list_point_add = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centroid_list_point_add.sizePolicy().hasHeightForWidth()
        )
        self.centroid_list_point_add.setSizePolicy(sizePolicy)
        self.centroid_list_point_add.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/plugins/ohsomeTools/img/icon_add.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.centroid_list_point_add.setIcon(icon2)
        self.centroid_list_point_add.setObjectName("centroid_list_point_add")
        self.gridLayout_7.addWidget(self.centroid_list_point_add, 0, 0, 1, 1)
        self.centroid_list_point_clear = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centroid_list_point_clear.sizePolicy().hasHeightForWidth()
        )
        self.centroid_list_point_clear.setSizePolicy(sizePolicy)
        self.centroid_list_point_clear.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/plugins/ohsomeTools/img/icon_clear.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.centroid_list_point_clear.setIcon(icon3)
        self.centroid_list_point_clear.setObjectName(
            "centroid_list_point_clear"
        )
        self.gridLayout_7.addWidget(self.centroid_list_point_clear, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_7, 1, 0, 1, 1)
        self.centroid_radius_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centroid_radius_label.sizePolicy().hasHeightForWidth()
        )
        self.centroid_radius_label.setSizePolicy(sizePolicy)
        self.centroid_radius_label.setObjectName("centroid_radius_label")
        self.gridLayout.addWidget(self.centroid_radius_label, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.widget, 0, 0, 1, 1)
        self.request_types_widget.addTab(self.centroid_tab, "")
        self.point_layer_tab = QtWidgets.QWidget()
        self.point_layer_tab.setEnabled(True)
        self.point_layer_tab.setObjectName("point_layer_tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.point_layer_tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_6 = QtWidgets.QWidget(self.point_layer_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_6.sizePolicy().hasHeightForWidth()
        )
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setAutoFillBackground(False)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.point_layer_list = QtWidgets.QListWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.point_layer_list.sizePolicy().hasHeightForWidth()
        )
        self.point_layer_list.setSizePolicy(sizePolicy)
        self.point_layer_list.setMinimumSize(QtCore.QSize(0, 0))
        self.point_layer_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.point_layer_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.point_layer_list.setSelectionMode(
            QtWidgets.QAbstractItemView.MultiSelection
        )
        self.point_layer_list.setResizeMode(QtWidgets.QListView.Fixed)
        self.point_layer_list.setObjectName("point_layer_list")
        self.gridLayout_5.addWidget(self.point_layer_list, 0, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_9.sizePolicy().hasHeightForWidth()
        )
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.point_layer_list_remove = QtWidgets.QPushButton(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.point_layer_list_remove.sizePolicy().hasHeightForWidth()
        )
        self.point_layer_list_remove.setSizePolicy(sizePolicy)
        self.point_layer_list_remove.setText("")
        self.point_layer_list_remove.setIcon(icon3)
        self.point_layer_list_remove.setObjectName("point_layer_list_remove")
        self.gridLayout_11.addWidget(self.point_layer_list_remove, 1, 0, 1, 1)
        self.point_layer_list_add = QtWidgets.QPushButton(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.point_layer_list_add.sizePolicy().hasHeightForWidth()
        )
        self.point_layer_list_add.setSizePolicy(sizePolicy)
        self.point_layer_list_add.setText("")
        self.point_layer_list_add.setIcon(icon2)
        self.point_layer_list_add.setObjectName("point_layer_list_add")
        self.gridLayout_11.addWidget(self.point_layer_list_add, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_9, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_6, 2, 0, 1, 4)
        self.point_layer_radius_input = QtWidgets.QSpinBox(self.point_layer_tab)
        self.point_layer_radius_input.setAccessibleDescription("")
        self.point_layer_radius_input.setMinimum(1)
        self.point_layer_radius_input.setMaximum(999999999)
        self.point_layer_radius_input.setProperty("value", 1000)
        self.point_layer_radius_input.setObjectName("point_layer_radius_input")
        self.gridLayout_12.addWidget(self.point_layer_radius_input, 0, 1, 2, 1)
        self.point_layer_radius_label = QtWidgets.QLabel(self.point_layer_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.point_layer_radius_label.sizePolicy().hasHeightForWidth()
        )
        self.point_layer_radius_label.setSizePolicy(sizePolicy)
        self.point_layer_radius_label.setObjectName("point_layer_radius_label")
        self.gridLayout_12.addWidget(self.point_layer_radius_label, 0, 0, 2, 1)
        self.point_layer_input = gui.QgsMapLayerComboBox(self.point_layer_tab)
        self.point_layer_input.setObjectName("point_layer_input")
        self.gridLayout_12.addWidget(self.point_layer_input, 0, 2, 2, 2)
        self.request_types_widget.addTab(self.point_layer_tab, "")
        self.polygon_layer_tab = QtWidgets.QWidget()
        self.polygon_layer_tab.setEnabled(True)
        self.polygon_layer_tab.setObjectName("polygon_layer_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.polygon_layer_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.layer_input = gui.QgsMapLayerComboBox(self.polygon_layer_tab)
        self.layer_input.setObjectName("layer_input")
        self.gridLayout_6.addWidget(self.layer_input, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.polygon_layer_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_5.sizePolicy().hasHeightForWidth()
        )
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layer_list = QtWidgets.QListWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.layer_list.sizePolicy().hasHeightForWidth()
        )
        self.layer_list.setSizePolicy(sizePolicy)
        self.layer_list.setMinimumSize(QtCore.QSize(0, 0))
        self.layer_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.layer_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.layer_list.setSelectionMode(
            QtWidgets.QAbstractItemView.MultiSelection
        )
        self.layer_list.setResizeMode(QtWidgets.QListView.Fixed)
        self.layer_list.setObjectName("layer_list")
        self.gridLayout_3.addWidget(self.layer_list, 0, 1, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_8.sizePolicy().hasHeightForWidth()
        )
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.layer_list_remove = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.layer_list_remove.sizePolicy().hasHeightForWidth()
        )
        self.layer_list_remove.setSizePolicy(sizePolicy)
        self.layer_list_remove.setText("")
        self.layer_list_remove.setIcon(icon3)
        self.layer_list_remove.setObjectName("layer_list_remove")
        self.gridLayout_9.addWidget(self.layer_list_remove, 1, 0, 1, 1)
        self.layer_list_add = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.layer_list_add.sizePolicy().hasHeightForWidth()
        )
        self.layer_list_add.setSizePolicy(sizePolicy)
        self.layer_list_add.setText("")
        self.layer_list_add.setIcon(icon2)
        self.layer_list_add.setObjectName("layer_list_add")
        self.gridLayout_9.addWidget(self.layer_list_add, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_8, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_5, 1, 0, 1, 1)
        self.request_types_widget.addTab(self.polygon_layer_tab, "")
        self.verticalLayout_5.addWidget(self.request_types_widget)
        self.configuration_group_box = gui.QgsCollapsibleGroupBox(
            OhsomeToolsDialogBase
        )
        self.configuration_group_box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.configuration_group_box.sizePolicy().hasHeightForWidth()
        )
        self.configuration_group_box.setSizePolicy(sizePolicy)
        self.configuration_group_box.setMaximumSize(QtCore.QSize(16777215, 28))
        self.configuration_group_box.setAutoFillBackground(False)
        self.configuration_group_box.setFlat(True)
        self.configuration_group_box.setCheckable(False)
        self.configuration_group_box.setChecked(False)
        self.configuration_group_box.setCollapsed(True)
        self.configuration_group_box.setScrollOnExpand(False)
        self.configuration_group_box.setSaveCollapsedState(False)
        self.configuration_group_box.setObjectName("configuration_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(
            self.configuration_group_box
        )
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.general_options_group = gui.QgsCollapsibleGroupBox(
            self.configuration_group_box
        )
        self.general_options_group.setCollapsed(True)
        self.general_options_group.setObjectName("general_options_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.general_options_group
        )
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.general_options_group)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.check_activate_temporal = QtWidgets.QCheckBox(self.frame_6)
        self.check_activate_temporal.setChecked(True)
        self.check_activate_temporal.setObjectName("check_activate_temporal")
        self.horizontalLayout_12.addWidget(self.check_activate_temporal)
        self.check_show_metadata = QtWidgets.QCheckBox(self.frame_6)
        self.check_show_metadata.setEnabled(True)
        self.check_show_metadata.setChecked(False)
        self.check_show_metadata.setObjectName("check_show_metadata")
        self.horizontalLayout_12.addWidget(self.check_show_metadata)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.general_options_group)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.check_merge_geometries = QtWidgets.QCheckBox(self.frame_8)
        self.check_merge_geometries.setEnabled(True)
        self.check_merge_geometries.setChecked(True)
        self.check_merge_geometries.setObjectName("check_merge_geometries")
        self.horizontalLayout_13.addWidget(self.check_merge_geometries)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_5 = QtWidgets.QFrame(self.general_options_group)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.timeout_label = QtWidgets.QLabel(self.frame_5)
        self.timeout_label.setObjectName("timeout_label")
        self.horizontalLayout_10.addWidget(self.timeout_label)
        self.timeout_input = QtWidgets.QSpinBox(self.frame_5)
        self.timeout_input.setAccessibleDescription("")
        self.timeout_input.setMinimum(0)
        self.timeout_input.setMaximum(9999999)
        self.timeout_input.setProperty("value", 0)
        self.timeout_input.setObjectName("timeout_input")
        self.horizontalLayout_10.addWidget(self.timeout_input)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_4.addWidget(self.general_options_group)
        self.intervals_group = gui.QgsCollapsibleGroupBox(
            self.configuration_group_box
        )
        self.intervals_group.setFlat(True)
        self.intervals_group.setCollapsed(True)
        self.intervals_group.setSaveCollapsedState(False)
        self.intervals_group.setObjectName("intervals_group")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.intervals_group)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.date_start = QtWidgets.QDateEdit(self.intervals_group)
        self.date_start.setDateTime(
            QtCore.QDateTime(QtCore.QDate(2016, 1, 1), QtCore.QTime(0, 0, 0))
        )
        self.date_start.setMinimumDateTime(
            QtCore.QDateTime(QtCore.QDate(2007, 10, 8), QtCore.QTime(0, 0, 0))
        )
        self.date_start.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.date_start.setMinimumDate(QtCore.QDate(2007, 10, 8))
        self.date_start.setTimeSpec(QtCore.Qt.LocalTime)
        self.date_start.setObjectName("date_start")
        self.gridLayout_10.addWidget(self.date_start, 5, 1, 1, 1)
        self.interval_months = QtWidgets.QSpinBox(self.intervals_group)
        self.interval_months.setMaximum(12)
        self.interval_months.setObjectName("interval_months")
        self.gridLayout_10.addWidget(self.interval_months, 3, 2, 1, 1)
        self.label_months = QtWidgets.QLabel(self.intervals_group)
        self.label_months.setToolTip("")
        self.label_months.setObjectName("label_months")
        self.gridLayout_10.addWidget(self.label_months, 2, 2, 1, 1)
        self.label_years = QtWidgets.QLabel(self.intervals_group)
        self.label_years.setToolTip("")
        self.label_years.setObjectName("label_years")
        self.gridLayout_10.addWidget(self.label_years, 2, 1, 1, 1)
        self.interval_days = QtWidgets.QSpinBox(self.intervals_group)
        self.interval_days.setMaximum(31)
        self.interval_days.setProperty("value", 1)
        self.interval_days.setObjectName("interval_days")
        self.gridLayout_10.addWidget(self.interval_days, 3, 4, 1, 1)
        self.date_end_label = QtWidgets.QLabel(self.intervals_group)
        self.date_end_label.setObjectName("date_end_label")
        self.gridLayout_10.addWidget(self.date_end_label, 4, 4, 1, 1)
        self.date_start_label = QtWidgets.QLabel(self.intervals_group)
        self.date_start_label.setObjectName("date_start_label")
        self.gridLayout_10.addWidget(self.date_start_label, 4, 1, 1, 1)
        self.label_days = QtWidgets.QLabel(self.intervals_group)
        self.label_days.setToolTip("")
        self.label_days.setObjectName("label_days")
        self.gridLayout_10.addWidget(self.label_days, 2, 4, 1, 1)
        self.date_end = QtWidgets.QDateEdit(self.intervals_group)
        self.date_end.setDateTime(
            QtCore.QDateTime(QtCore.QDate(2017, 1, 1), QtCore.QTime(0, 0, 0))
        )
        self.date_end.setMinimumDateTime(
            QtCore.QDateTime(QtCore.QDate(2007, 10, 9), QtCore.QTime(0, 0, 0))
        )
        self.date_end.setMinimumDate(QtCore.QDate(2007, 10, 9))
        self.date_end.setObjectName("date_end")
        self.gridLayout_10.addWidget(self.date_end, 5, 4, 1, 1)
        self.interval_years = QtWidgets.QSpinBox(self.intervals_group)
        self.interval_years.setAccessibleDescription("")
        self.interval_years.setMaximum(99)
        self.interval_years.setProperty("value", 0)
        self.interval_years.setObjectName("interval_years")
        self.gridLayout_10.addWidget(self.interval_years, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.intervals_group)
        self.property_groups_box = gui.QgsCollapsibleGroupBox(
            self.configuration_group_box
        )
        self.property_groups_box.setFlat(True)
        self.property_groups_box.setCollapsed(True)
        self.property_groups_box.setObjectName("property_groups_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.property_groups_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.property_groups_box)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_clip_geometry = QtWidgets.QCheckBox(self.frame_7)
        self.check_clip_geometry.setEnabled(True)
        self.check_clip_geometry.setChecked(True)
        self.check_clip_geometry.setObjectName("check_clip_geometry")
        self.horizontalLayout.addWidget(self.check_clip_geometry)
        self.check_keep_geometryless = QtWidgets.QCheckBox(self.frame_7)
        self.check_keep_geometryless.setEnabled(True)
        self.check_keep_geometryless.setChecked(False)
        self.check_keep_geometryless.setObjectName("check_keep_geometryless")
        self.horizontalLayout.addWidget(self.check_keep_geometryless)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.property_groups_groupbox = QtWidgets.QGroupBox(
            self.property_groups_box
        )
        self.property_groups_groupbox.setFlat(False)
        self.property_groups_groupbox.setCheckable(False)
        self.property_groups_groupbox.setObjectName("property_groups_groupbox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(
            self.property_groups_groupbox
        )
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.property_groups_groupbox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.property_groups_check_metadata = QtWidgets.QCheckBox(self.frame_4)
        self.property_groups_check_metadata.setObjectName(
            "property_groups_check_metadata"
        )
        self.horizontalLayout_2.addWidget(self.property_groups_check_metadata)
        self.property_groups_check_tags = QtWidgets.QCheckBox(self.frame_4)
        self.property_groups_check_tags.setChecked(True)
        self.property_groups_check_tags.setObjectName(
            "property_groups_check_tags"
        )
        self.horizontalLayout_2.addWidget(self.property_groups_check_tags)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.verticalLayout_6.addWidget(self.property_groups_groupbox)
        self.verticalLayout_4.addWidget(self.property_groups_box)
        self.data_aggregation_group = gui.QgsCollapsibleGroupBox(
            self.configuration_group_box
        )
        self.data_aggregation_group.setCollapsed(True)
        self.data_aggregation_group.setObjectName("data_aggregation_group")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(
            self.data_aggregation_group
        )
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame = QtWidgets.QFrame(self.data_aggregation_group)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.data_aggregation_format = QtWidgets.QComboBox(self.frame)
        self.data_aggregation_format.setObjectName("data_aggregation_format")
        self.horizontalLayout_9.addWidget(self.data_aggregation_format)
        self.verticalLayout_9.addWidget(self.frame)
        self.group_by_frame = QtWidgets.QFrame(self.data_aggregation_group)
        self.group_by_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_by_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_by_frame.setObjectName("group_by_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_by_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filter_frame_2 = QtWidgets.QFrame(self.group_by_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_frame_2.sizePolicy().hasHeightForWidth()
        )
        self.filter_frame_2.setSizePolicy(sizePolicy)
        self.filter_frame_2.setToolTip("")
        self.filter_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame_2.setObjectName("filter_frame_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.filter_frame_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.group_by_keys_label = QtWidgets.QLabel(self.filter_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.group_by_keys_label.sizePolicy().hasHeightForWidth()
        )
        self.group_by_keys_label.setSizePolicy(sizePolicy)
        self.group_by_keys_label.setObjectName("group_by_keys_label")
        self.horizontalLayout_11.addWidget(self.group_by_keys_label)
        self.group_by_key_line_edit = QtWidgets.QLineEdit(self.filter_frame_2)
        self.group_by_key_line_edit.setText("")
        self.group_by_key_line_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.group_by_key_line_edit.setObjectName("group_by_key_line_edit")
        self.horizontalLayout_11.addWidget(self.group_by_key_line_edit)
        self.verticalLayout.addWidget(self.filter_frame_2)
        self.filter_frame_3 = QtWidgets.QFrame(self.group_by_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_frame_3.sizePolicy().hasHeightForWidth()
        )
        self.filter_frame_3.setSizePolicy(sizePolicy)
        self.filter_frame_3.setToolTip("")
        self.filter_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame_3.setObjectName("filter_frame_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.filter_frame_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.group_by_values_label = QtWidgets.QLabel(self.filter_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.group_by_values_label.sizePolicy().hasHeightForWidth()
        )
        self.group_by_values_label.setSizePolicy(sizePolicy)
        self.group_by_values_label.setObjectName("group_by_values_label")
        self.horizontalLayout_14.addWidget(self.group_by_values_label)
        self.group_by_values_line_edit = QtWidgets.QLineEdit(
            self.filter_frame_3
        )
        self.group_by_values_line_edit.setObjectName(
            "group_by_values_line_edit"
        )
        self.horizontalLayout_14.addWidget(self.group_by_values_line_edit)
        self.verticalLayout.addWidget(self.filter_frame_3)
        self.filter_frame_4 = QtWidgets.QFrame(self.group_by_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_frame_4.sizePolicy().hasHeightForWidth()
        )
        self.filter_frame_4.setSizePolicy(sizePolicy)
        self.filter_frame_4.setToolTip("")
        self.filter_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame_4.setObjectName("filter_frame_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.filter_frame_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.filter2_input_label = QtWidgets.QLabel(self.filter_frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter2_input_label.sizePolicy().hasHeightForWidth()
        )
        self.filter2_input_label.setSizePolicy(sizePolicy)
        self.filter2_input_label.setObjectName("filter2_input_label")
        self.horizontalLayout_15.addWidget(self.filter2_input_label)
        self.filter2_input = QtWidgets.QLineEdit(self.filter_frame_4)
        self.filter2_input.setAutoFillBackground(False)
        self.filter2_input.setStyleSheet("")
        self.filter2_input.setObjectName("filter2_input")
        self.horizontalLayout_15.addWidget(self.filter2_input)
        self.verticalLayout.addWidget(self.filter_frame_4)
        self.verticalLayout_9.addWidget(self.group_by_frame)
        self.verticalLayout_4.addWidget(self.data_aggregation_group)
        self.verticalLayout_5.addWidget(self.configuration_group_box)
        self.filter_frame = QtWidgets.QFrame(OhsomeToolsDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_frame.sizePolicy().hasHeightForWidth()
        )
        self.filter_frame.setSizePolicy(sizePolicy)
        self.filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame.setObjectName("filter_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.filter_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.filter_label = QtWidgets.QLabel(self.filter_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_label.sizePolicy().hasHeightForWidth()
        )
        self.filter_label.setSizePolicy(sizePolicy)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout_6.addWidget(self.filter_label)
        self.filter_input = QtWidgets.QPlainTextEdit(self.filter_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Maximum,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.filter_input.sizePolicy().hasHeightForWidth()
        )
        self.filter_input.setSizePolicy(sizePolicy)
        self.filter_input.setMaximumSize(QtCore.QSize(331, 101))
        self.filter_input.setPlainText("")
        self.filter_input.setObjectName("filter_input")
        self.horizontalLayout_6.addWidget(self.filter_input)
        self.verticalLayout_5.addWidget(self.filter_frame)
        self.ohsome_log_group = gui.QgsCollapsibleGroupBox(
            OhsomeToolsDialogBase
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ohsome_log_group.sizePolicy().hasHeightForWidth()
        )
        self.ohsome_log_group.setSizePolicy(sizePolicy)
        self.ohsome_log_group.setMinimumSize(QtCore.QSize(0, 0))
        self.ohsome_log_group.setMaximumSize(QtCore.QSize(16777215, 28))
        self.ohsome_log_group.setFlat(True)
        self.ohsome_log_group.setCollapsed(True)
        self.ohsome_log_group.setSaveCollapsedState(False)
        self.ohsome_log_group.setObjectName("ohsome_log_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ohsome_log_group)
        self.verticalLayout_2.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.debug_text = QtWidgets.QTextBrowser(self.ohsome_log_group)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.debug_text.sizePolicy().hasHeightForWidth()
        )
        self.debug_text.setSizePolicy(sizePolicy)
        self.debug_text.setMinimumSize(QtCore.QSize(0, 80))
        self.debug_text.setMaximumSize(QtCore.QSize(16777215, 80))
        self.debug_text.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.debug_text.setTabStopWidth(80)
        self.debug_text.setOpenExternalLinks(True)
        self.debug_text.setObjectName("debug_text")
        self.verticalLayout_2.addWidget(self.debug_text)
        self.verticalLayout_5.addWidget(self.ohsome_log_group)
        self.control_widget = QtWidgets.QWidget(OhsomeToolsDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.control_widget.sizePolicy().hasHeightForWidth()
        )
        self.control_widget.setSizePolicy(sizePolicy)
        self.control_widget.setObjectName("control_widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.control_widget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.help_button = QtWidgets.QPushButton(self.control_widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.help_button.sizePolicy().hasHeightForWidth()
        )
        self.help_button.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/plugins/ohsomeTools/img/icon_help.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.help_button.setIcon(icon4)
        self.help_button.setObjectName("help_button")
        self.horizontalLayout_8.addWidget(self.help_button)
        self.about_button = QtWidgets.QPushButton(self.control_widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/plugins/ohsomeTools/img/icon_about.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.about_button.setIcon(icon5)
        self.about_button.setObjectName("about_button")
        self.horizontalLayout_8.addWidget(self.about_button)
        self.global_buttons = QtWidgets.QDialogButtonBox(self.control_widget)
        self.global_buttons.setEnabled(True)
        self.global_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.global_buttons.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.global_buttons.setObjectName("global_buttons")
        self.horizontalLayout_8.addWidget(self.global_buttons)
        self.verticalLayout_5.addWidget(self.control_widget)
        self.resources_group.raise_()
        self.control_widget.raise_()
        self.ohsome_log_group.raise_()
        self.request_types_widget.raise_()
        self.configuration_group_box.raise_()
        self.groupBox_4.raise_()
        self.filter_frame.raise_()

        self.retranslateUi(OhsomeToolsDialogBase)
        self.request_types_widget.setCurrentIndex(0)
        self.global_buttons.accepted.connect(OhsomeToolsDialogBase.accept)
        self.global_buttons.rejected.connect(OhsomeToolsDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(OhsomeToolsDialogBase)

    def retranslateUi(self, OhsomeToolsDialogBase):
        _translate = QtCore.QCoreApplication.translate
        OhsomeToolsDialogBase.setWindowTitle(
            _translate("OhsomeToolsDialogBase", "ohsomeTools")
        )
        self.resources_group.setTitle(
            _translate("OhsomeToolsDialogBase", "Resources")
        )
        self.api_label.setText(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p><a href="https://docs.ohsome.org/ohsome-api/stable/"><span style=" font-size:12pt; font-weight:600; text-decoration: underline; color:#2eb8e6;">API DOCS</span></a></p></body></html>',
            )
        )
        self.ohsome_label.setText(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p><a href="https://heigit.org/big-spatial-data-analytics-en/ohsome/"><span style=" font-size:14pt; font-weight:600; text-decoration: underline; color:#2eb8e6;">OHSOME</span></a></p></body></html>',
            )
        )
        self.hex_label.setText(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p><a href="https://ohsome.org/apps/osm-history-explorer/"><span style=" font-size:12pt; font-weight:600; text-decoration: underline; color:#2eb8e6;">HEX</span></a></p></body></html>',
            )
        )
        self.groupBox_4.setTitle(
            _translate("OhsomeToolsDialogBase", "Endpoint Selections")
        )
        self.label_15.setText(_translate("OhsomeToolsDialogBase", "Provider"))
        self.provider_refresh.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "Refresh the provider list. Needed after a provider was added or deleted.",
            )
        )
        self.provider_config.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "Shortcut to Web ► ohsomeTools ► Provider Settings",
            )
        )
        self.ohsome_spec_selection_combo.setToolTip(
            _translate("OhsomeToolsDialogBase", "ohsome API Endpoint")
        )
        self.ohsome_spec_preference_combo.setToolTip(
            _translate("OhsomeToolsDialogBase", "Request preference")
        )
        self.ohsome_spec_preference_combo.setPlaceholderText(
            _translate("OhsomeToolsDialogBase", "Spec")
        )
        self.ohsome_spec_preference_specification.setToolTip(
            _translate("OhsomeToolsDialogBase", "Request preference")
        )
        self.centroid_radius_input.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Add a centroid radius <span style=" text-decoration: underline;">in meters</span> per centroid. Default is <span style=" text-decoration: underline;">10 meters</span>.</p></body></html>',
            )
        )
        self.ohsome_centroid_location_list.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "Select centroids from the map with the given radius!",
            )
        )
        self.centroid_list_point_add.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Add centroids interactively from the map canvas.</p><p>Double-click will terminate centroid selection.</p></body></html>",
            )
        )
        self.centroid_list_point_clear.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>If centroids are selected in the list, only these will be deleted. Else all centroids will be deleted.</p></body></html>",
            )
        )
        self.centroid_radius_label.setText(
            _translate("OhsomeToolsDialogBase", "Radius")
        )
        self.request_types_widget.setTabText(
            self.request_types_widget.indexOf(self.centroid_tab),
            _translate("OhsomeToolsDialogBase", "Centroid"),
        )
        self.point_layer_list.setToolTip(
            _translate(
                "OhsomeToolsDialogBase", "Select layers from your layer list!"
            )
        )
        self.point_layer_list_remove.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>If layers are selected in the list, only these will be deleted.</p></body></html>",
            )
        )
        self.point_layer_list_add.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Add layers interactively from your layer list.</p></body></html>",
            )
        )
        self.point_layer_radius_input.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Add a centroid radius <span style=" text-decoration: underline;">in meters</span> per centroid. Default is <span style=" text-decoration: underline;">10 meters</span>.</p></body></html>',
            )
        )
        self.point_layer_radius_label.setText(
            _translate("OhsomeToolsDialogBase", "Radius")
        )
        self.point_layer_input.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Select Polygon / MultiPolygon layers to query with.</p></body></html>",
            )
        )
        self.request_types_widget.setTabText(
            self.request_types_widget.indexOf(self.point_layer_tab),
            _translate("OhsomeToolsDialogBase", "Point Layer"),
        )
        self.layer_input.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Select Polygon / MultiPolygon layers to query with.</p></body></html>",
            )
        )
        self.layer_list.setToolTip(
            _translate(
                "OhsomeToolsDialogBase", "Select layers from your layer list!"
            )
        )
        self.layer_list_remove.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>If layers are selected in the list, only these will be deleted.</p></body></html>",
            )
        )
        self.layer_list_add.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Add layers interactively from your layer list.</p></body></html>",
            )
        )
        self.request_types_widget.setTabText(
            self.request_types_widget.indexOf(self.polygon_layer_tab),
            _translate("OhsomeToolsDialogBase", "Polygon layer"),
        )
        self.configuration_group_box.setTitle(
            _translate("OhsomeToolsDialogBase", "Configuration")
        )
        self.general_options_group.setTitle(
            _translate("OhsomeToolsDialogBase", "General")
        )
        self.check_activate_temporal.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Automatically enable the temporal feature for new layers where applicable.</p><p><br/></p><p>This is only applied to responses that contain geometries and in that manner only on those geometry layers it makes sense for.</p></body></html>",
            )
        )
        self.check_activate_temporal.setText(
            _translate("OhsomeToolsDialogBase", "Qgis temporal feature")
        )
        self.check_show_metadata.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Include metadata into the query response. Depending on the request of the request this can increase the response data size significantly.</p></body></html>",
            )
        )
        self.check_show_metadata.setText(
            _translate("OhsomeToolsDialogBase", "Show metadata")
        )
        self.check_merge_geometries.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Check this to <span style=" text-decoration: underline;">automatically merge compatible geometry types</span>. </p><p><span style=" text-decoration: underline;">It is recommended to keep this checked.</span></p><p>The benefit is that the amount of written layers will be massively reduced.</p><p>The reason is that results may contain single and multi-geometries at once (Polygon, MultiPolygon etc.) and without combining them one layer per geometry type will be written, resulting in an increased number of layers. </p><p><br/></p></body></html>',
            )
        )
        self.check_merge_geometries.setText(
            _translate("OhsomeToolsDialogBase", "Harmonize geometries")
        )
        self.timeout_label.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Apply a request <span style=" text-decoration: underline;">timeout in seconds</span> after that the ohsome API should terminate the request.</p><p>For the public ohsome API instance the maximum value is 100. For private instances there is no maximum.</p></body></html>',
            )
        )
        self.timeout_label.setText(
            _translate("OhsomeToolsDialogBase", "Timeout")
        )
        self.timeout_input.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Apply a request <span style=" text-decoration: underline;">timeout in seconds</span> after that the ohsome API should terminate the request. If the value 0 is set (default), the server side timeout is used automatically, which can be up to 600 seconds.</p><p>Depending on the size of the query, too low entries will yield API errors.</p><p>This setting is only used for the public ohsome API and not for private ones.</p></body></html>',
            )
        )
        self.intervals_group.setTitle(
            _translate("OhsomeToolsDialogBase", "Intervals")
        )
        self.date_start.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Enter your start date. </p><p><br/></p><p>All <span style=" text-decoration: underline;">dates from the </span><span style=" font-weight:600; text-decoration: underline;">8th</span><span style=" text-decoration: underline;"> of Oktober 2007</span> are valid.</p></body></html>',
            )
        )
        self.date_start.setDisplayFormat(
            _translate("OhsomeToolsDialogBase", "dd-MM-yyyy")
        )
        self.interval_months.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Run the query every x months. Adjust the time frame accordingly.</p><p><br/></p><p>Only available for the data aggregation endpoints.</p></body></html>",
            )
        )
        self.label_months.setText(_translate("OhsomeToolsDialogBase", "Months"))
        self.label_years.setText(_translate("OhsomeToolsDialogBase", "Years"))
        self.interval_days.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Run the query every x days. Adjust the time frame accordingly.</p><p><br/></p><p>Only available for the data aggregation endpoints.</p></body></html>",
            )
        )
        self.date_end_label.setText(
            _translate("OhsomeToolsDialogBase", "Date End")
        )
        self.date_start_label.setText(
            _translate("OhsomeToolsDialogBase", "Date Start")
        )
        self.label_days.setText(_translate("OhsomeToolsDialogBase", "Days"))
        self.date_end.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Enter your end date. </p><p><br/></p><p>All <span style=" text-decoration: underline;">dates from the </span><span style=" font-weight:600; text-decoration: underline;">9th</span><span style=" text-decoration: underline;"> of Oktober 2007</span> are valid.</p></body></html>',
            )
        )
        self.date_end.setDisplayFormat(
            _translate("OhsomeToolsDialogBase", "dd-MM-yyyy")
        )
        self.interval_years.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Run the query every <span style=" text-decoration: underline;">x</span> years. Adjust the time frame accordingly.</p><p>Only available for the data aggregation endpoints.</p></body></html>',
            )
        )
        self.property_groups_box.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>List of possible property-groups added to each OSM-element.</p><p>Only available for data extraction.</p></body></html>",
            )
        )
        self.property_groups_box.setTitle(
            _translate("OhsomeToolsDialogBase", "Data extraction")
        )
        self.check_clip_geometry.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Specify whether the returned geometries of the features should be clipped to the query’s spatial boundary.</p><p><span style=" text-decoration: underline;">Ony available for the data extraction endpoints</span>.</p></body></html>',
            )
        )
        self.check_clip_geometry.setText(
            _translate("OhsomeToolsDialogBase", "Clip Geometry")
        )
        self.check_keep_geometryless.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Some results don't contain geometries but metadata.</p><p>Decide if you wan't to keep them or only return ones with geometries.</p><p>If checked, the geometry less features will be stored separately.</p></body></html>",
            )
        )
        self.check_keep_geometryless.setText(
            _translate("OhsomeToolsDialogBase", "Keep without geometry")
        )
        self.property_groups_groupbox.setTitle(
            _translate("OhsomeToolsDialogBase", "Property Groups")
        )
        self.property_groups_check_metadata.setText(
            _translate("OhsomeToolsDialogBase", "Metadata")
        )
        self.property_groups_check_tags.setText(
            _translate("OhsomeToolsDialogBase", "Tags")
        )
        self.data_aggregation_group.setTitle(
            _translate("OhsomeToolsDialogBase", "Data aggregation")
        )
        self.label.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Output format geojson (for /groupBy/boundary resources only), or json.</p></body></html>",
            )
        )
        self.label.setText(_translate("OhsomeToolsDialogBase", "Format"))
        self.data_aggregation_format.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>Output format geojson (for /groupBy/boundary resources only), or json.</p></body></html>",
            )
        )
        self.group_by_keys_label.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>OSM key e.g.: 'highway’, 'building’; no default value (one groupByKey parameter must be defined).</p><p><span style=\" text-decoration: underline;\">Only for `groupBy/tag` endpoints.</span></p></body></html>",
            )
        )
        self.group_by_keys_label.setText(
            _translate("OhsomeToolsDialogBase", "groupByKey")
        )
        self.group_by_key_line_edit.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>OSM key e.g.: 'highway’, 'building’; no default value (one groupByKey parameter must be defined).</p><p><span style=\" text-decoration: underline;\">Only for `groupBy/tag` and `groupBy/key` endpoints.</span></p></body></html>",
            )
        )
        self.group_by_key_line_edit.setPlaceholderText(
            _translate("OhsomeToolsDialogBase", "building")
        )
        self.group_by_values_label.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>OSM value(s) e.g.: 'primary’, 'residential’; default: no value. Can be left empty.</p><p><span style=\" text-decoration: underline;\">Only for `groupBy/tag` endpoints.</span></p></body></html>",
            )
        )
        self.group_by_values_label.setText(
            _translate("OhsomeToolsDialogBase", "groupByValues")
        )
        self.group_by_values_line_edit.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                "<html><head/><body><p>OSM value(s) e.g.: 'primary’, 'residential’; default: no value. Can be left empty.</p><p><span style=\" text-decoration: underline;\">Only for `groupBy/tag` endpoints.</span></p></body></html>",
            )
        )
        self.filter2_input_label.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Combines several attributive filters, e.g. OSM type, the geometry (simple feature) type, as well as the OSM tag; no default value</p><p><span style=" text-decoration: underline;">Only for `ratio` endpoints.</span></p></body></html>',
            )
        )
        self.filter2_input_label.setText(
            _translate("OhsomeToolsDialogBase", "Filter 2")
        )
        self.filter2_input.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Combines several attributive filters, e.g. OSM type, the geometry (simple feature) type, as well as the OSM tag; no default value</p><p><span style=" text-decoration: underline;">Only for `ratio` endpoints.</span></p></body></html>',
            )
        )
        self.filter_label.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Combines several attributive filters, e.g. OSM type, the geometry (simple feature) type, as well as the OSM tag. </p><p>For more information see: <a href="https://docs.ohsome.org/ohsome-api/v1/filter.html"><span style=" text-decoration: underline; color:#2eb8e6;">https://docs.ohsome.org/ohsome-api/v1/filter.html</span></a></p></body></html>',
            )
        )
        self.filter_label.setText(
            _translate("OhsomeToolsDialogBase", "Filter  ")
        )
        self.filter_input.setToolTip(
            _translate(
                "OhsomeToolsDialogBase",
                '<html><head/><body><p>Combines several attributive filters, e.g. OSM type, the geometry (simple feature) type, as well as the OSM tag. </p><p>For more information see: <a href="https://docs.ohsome.org/ohsome-api/v1/filter.html"><span style=" text-decoration: underline; color:#2eb8e6;">https://docs.ohsome.org/ohsome-api/v1/filter.html</span></a></p></body></html>',
            )
        )
        self.filter_input.setPlaceholderText(
            _translate(
                "OhsomeToolsDialogBase",
                "building=* or (type:way and highway=residential)",
            )
        )
        self.ohsome_log_group.setTitle(
            _translate("OhsomeToolsDialogBase", "Log")
        )
        self.debug_text.setPlaceholderText(
            _translate(
                "OhsomeToolsDialogBase",
                "Queries and errors will be printed here.",
            )
        )
        self.help_button.setText(_translate("OhsomeToolsDialogBase", "  Help"))
        self.about_button.setText(_translate("OhsomeToolsDialogBase", "About"))


from qgis import gui
from . import resources_rc
