# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OhsomeToolsDialogConfigUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OhsomeToolsDialogConfigBase(object):
    def setupUi(self, OhsomeToolsDialogConfigBase):
        OhsomeToolsDialogConfigBase.setObjectName("OhsomeToolsDialogConfigBase")
        OhsomeToolsDialogConfigBase.resize(414, 67)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            OhsomeToolsDialogConfigBase.sizePolicy().hasHeightForWidth()
        )
        OhsomeToolsDialogConfigBase.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(OhsomeToolsDialogConfigBase)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.providers = QtWidgets.QWidget(OhsomeToolsDialogConfigBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.providers.sizePolicy().hasHeightForWidth()
        )
        self.providers.setSizePolicy(sizePolicy)
        self.providers.setObjectName("providers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.providers)
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.providers, 0, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(OhsomeToolsDialogConfigBase)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.provider_add = QtWidgets.QPushButton(OhsomeToolsDialogConfigBase)
        self.provider_add.setObjectName("provider_add")
        self.gridLayout.addWidget(self.provider_add, 1, 0, 1, 1)
        self.provider_remove = QtWidgets.QPushButton(
            OhsomeToolsDialogConfigBase
        )
        self.provider_remove.setObjectName("provider_remove")
        self.gridLayout.addWidget(self.provider_remove, 1, 1, 1, 1)

        self.retranslateUi(OhsomeToolsDialogConfigBase)
        QtCore.QMetaObject.connectSlotsByName(OhsomeToolsDialogConfigBase)

    def retranslateUi(self, OhsomeToolsDialogConfigBase):
        _translate = QtCore.QCoreApplication.translate
        OhsomeToolsDialogConfigBase.setWindowTitle(
            _translate("OhsomeToolsDialogConfigBase", "Provider Settings")
        )
        self.provider_add.setText(
            _translate("OhsomeToolsDialogConfigBase", "Add")
        )
        self.provider_remove.setText(
            _translate("OhsomeToolsDialogConfigBase", "Remove")
        )
