# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ohsomeTools/gui/OhsomeQgisDialogConfigUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OhsomeQgisDialogConfigBase(object):
    def setupUi(self, OhsomeQgisDialogConfigBase):
        OhsomeQgisDialogConfigBase.setObjectName("OhsomeQgisDialogConfigBase")
        OhsomeQgisDialogConfigBase.resize(414, 67)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            OhsomeQgisDialogConfigBase.sizePolicy().hasHeightForWidth()
        )
        OhsomeQgisDialogConfigBase.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(OhsomeQgisDialogConfigBase)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.providers = QtWidgets.QWidget(OhsomeQgisDialogConfigBase)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.providers.sizePolicy().hasHeightForWidth()
        )
        self.providers.setSizePolicy(sizePolicy)
        self.providers.setObjectName("providers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.providers)
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.providers, 0, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(OhsomeQgisDialogConfigBase)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.provider_add = QtWidgets.QPushButton(OhsomeQgisDialogConfigBase)
        self.provider_add.setObjectName("provider_add")
        self.gridLayout.addWidget(self.provider_add, 1, 0, 1, 1)
        self.provider_remove = QtWidgets.QPushButton(OhsomeQgisDialogConfigBase)
        self.provider_remove.setObjectName("provider_remove")
        self.gridLayout.addWidget(self.provider_remove, 1, 1, 1, 1)

        self.retranslateUi(OhsomeQgisDialogConfigBase)
        QtCore.QMetaObject.connectSlotsByName(OhsomeQgisDialogConfigBase)

    def retranslateUi(self, OhsomeQgisDialogConfigBase):
        _translate = QtCore.QCoreApplication.translate
        OhsomeQgisDialogConfigBase.setWindowTitle(
            _translate("OhsomeQgisDialogConfigBase", "Provider Settings")
        )
        self.provider_add.setText(
            _translate("OhsomeQgisDialogConfigBase", "Add")
        )
        self.provider_remove.setText(
            _translate("OhsomeQgisDialogConfigBase", "Remove")
        )
